### ISSUE TITLE
Algorithmiaio

### ISSUE THREAD

**Issue by ashu-22** [anowell/mia#19]
When I downloaded the algorithmia-v1.01- ...zip I have got some virus for the running this program.Can you please tell me.How could I implement something?So, I could not get any kind of virus there.

**Comment by anowell** [comment]
I'm not sure I fully understand the question.

The releases when downloaded from [here])(https://github.com/algorithmiaio/algorithmia-cli/releases) should be safe. If your system has a clean virus scan right before downloading it, and then claims a virus once you download it, I'd be interested to know what platform, and virus scanner caused it so we can investigate and report it as a false positive. Of course, if your system already had a virus, it's possible that it infected the Algorithmia CLI on your computer.

If you're concerned that the Algorithmia CLI caused you to get a virus from calling an algorithm, that shouldn't be possible. All the Algorithmia algorithms run on our server, not your computer, and this CLI just fetches the response (usually JSON text) and prints or saves it.

If none of that is helpful, please provide additional details to clarify your question. Thanks!

**Comment by ashu-22** [comment]
Yes, Thanks for responding.As I wrote your specifically that I have written down that When I downloaded the Algorithmia zip.It contains a virus, That does not work out very well in my system.So, I have used my antivirus for it for solving this problem.But, I was helpless to work out on that way.Until I try another approach to uninstall that antivirus that is creating a problem.

**Comment by ashu-22** [comment]
Hopefully, you will understand the situation very well that I was facing there to solve something on my own.

**Comment by anowell** [comment]
I just downloaded and scanned the zips for Windows to confirm. You can see the results [here](https://www.virustotal.com/en/file/a6e47cb0039e116c74d71ab6b99482f45b14a8dc0af65d1f273651f56c580f64/analysis/1502383631/) and [here](https://www.virustotal.com/en/file/895682825dd2024d4ad0cdf277d21a631f14ee41ad7c33ae3292b034bff6c87e/analysis/1502383596/). I'm sorry to hear that your antivirus is reporting a virus, but it is most likely because something else on your computer was infected first.
